config/routes.rb
RorAzureDemo::Application.routes.draw do
  resources :searches

  root "home#index"
  get "home/index"

  resources :searches

end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @searches = Search.all
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to action: 'index' }
        format.json { render action: 'show', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keyword)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, page_title.to_s
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/home/index.html.erb
<h1><%= yield(:title) %></h1>

<p class="lead">Just a quick and simple demo app to test deployments to Windows Azure Virtual Machines.</p>

<a href="<%= new_search_path %>"  class="btn btn-default">Add a new keyword</a>
<hr/>
<div id="twitterfeed" class="container">
  <div class="row">
    <div class="col-md-4">
      <ul class="list-group">
        <% @searches.each do |s| %>
          <li class="list-group-item">
            <span class="badge">0</span>
            <%= s.keyword %>
          </li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-8">
      <div class="alert alert-warning"><strong>Todo:</strong> Implement a twitter client here :)</div>
    </div>
  </div>
</div>

<% content_for :footer do %>
  <%= javascript_include_tag "twitter.feed" %>
<% end %>

app/views/layouts/application.html.erb
<% title "Windows Azure Ruby on Rails Demo App" %>

<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= yield(:title) %></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/">Home</a></li>
            <li class="active"><%= link_to "Manage Keywords", searches_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
      <div class="starter-template">
        <%= yield %>
      </div>
    </div><!-- /.container -->

    <%= yield :footer %>
</body>
</html>

app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keyword %><br>
    <%= f.text_field :keyword %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing search</h1>

<%= render 'form' %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<table class="table table-striped searches">
  <thead>
    <tr>
      <th>Keywords</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.keyword %></td>
        <td><%= link_to 'Edit', edit_search_path(search), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', search, method: :delete, class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Search Keyword', new_search_path, class: "btn btn-warning" %>

app/views/searches/new.html.erb
<%= form_for @search, url: {action: "create"}, :html => { :class => "form-horizontal" }  do |f| %>
  <fieldset>
    <legend>New Search Keyword</legend>

    <div class="form-group">
      <%= f.label :keyword, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_field :keyword, class: "form-control" %></p>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit 'Add new keyword', class: "btn btn-default" %>
      </div>
    </div>
  </fieldset>
<% end %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Keyword:</strong>
  <%= @search.keyword %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>